# Generated by Django 5.0.6 on 2024-06-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_reservation_number_of_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Canceled', 'Canceled'), ('Completed', 'Completed')], default='Scheduled', max_length=20),
        ),
    ]
